# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Korthex < Formula
  desc "AI-native Kubernetes TUI tool - speak to your cluster, see everything"
  homepage "https://github.com/Orwell-Yu/korthex"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Orwell-Yu/korthex/releases/download/v0.2.0/korthex_0.2.0_darwin_amd64.tar.gz"
      sha256 "b54b83ddadae1dba67ccec320bbcffb850c9d59a1e9d063adad401b2b873e706"

      define_method(:install) do
        bin.install "korthex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Orwell-Yu/korthex/releases/download/v0.2.0/korthex_0.2.0_darwin_arm64.tar.gz"
      sha256 "d60fe0763d7a64cf100d17f6858d541f89bfe05c0729aff09648c1b6ed8034ee"

      define_method(:install) do
        bin.install "korthex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Orwell-Yu/korthex/releases/download/v0.2.0/korthex_0.2.0_linux_amd64.tar.gz"
      sha256 "a7510dd4d5ca57a21a55a0fcc28b2f7c5a97df50dd014a2cff756cfd30b202b8"
      define_method(:install) do
        bin.install "korthex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Orwell-Yu/korthex/releases/download/v0.2.0/korthex_0.2.0_linux_arm64.tar.gz"
      sha256 "5b8db954833150249e0b8e1879a9cee5feb6aecd7aa19ba12800bfa3c0762ec1"
      define_method(:install) do
        bin.install "korthex"
      end
    end
  end

  test do
    system "#{bin}/korthex", "--version"
  end
end
