# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Korthex < Formula
  desc "AI-native Kubernetes TUI tool - speak to your cluster, see everything"
  homepage "https://github.com/Orwell-Yu/korthex"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Orwell-Yu/korthex/releases/download/v0.3.0/korthex_0.3.0_darwin_amd64.tar.gz"
      sha256 "a3dedccc370a8d8147785c2dcc9f917d4f10538decfcccac584a7b7c426f3663"

      define_method(:install) do
        bin.install "korthex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Orwell-Yu/korthex/releases/download/v0.3.0/korthex_0.3.0_darwin_arm64.tar.gz"
      sha256 "e58aa9f593088bf8d364710fca611cb5e7deea84e67990521e9b8e7732556f0b"

      define_method(:install) do
        bin.install "korthex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Orwell-Yu/korthex/releases/download/v0.3.0/korthex_0.3.0_linux_amd64.tar.gz"
      sha256 "454b33e4b376835eb1cf93fd956ac6e4279fabb942c473646e17355c37bc3d22"
      define_method(:install) do
        bin.install "korthex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Orwell-Yu/korthex/releases/download/v0.3.0/korthex_0.3.0_linux_arm64.tar.gz"
      sha256 "6d6d88ce7371710ee7c47492e1f23ad0c965f8db65cbab82f0c8d37276650e9c"
      define_method(:install) do
        bin.install "korthex"
      end
    end
  end

  test do
    system "#{bin}/korthex", "--version"
  end
end
