# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Korthex < Formula
  desc "AI-native Kubernetes TUI tool - speak to your cluster, see everything"
  homepage "https://github.com/Orwell-Yu/korthex"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Orwell-Yu/korthex/releases/download/v0.1.0/korthex_0.1.0_darwin_amd64.tar.gz"
      sha256 "74b56db330e274bb8399226e1be6e708e85211e526fbd688caf3d4cb2f475c5b"

      define_method(:install) do
        bin.install "korthex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Orwell-Yu/korthex/releases/download/v0.1.0/korthex_0.1.0_darwin_arm64.tar.gz"
      sha256 "2566f778e7557f9b68efe202f7c302a44f56a96f59acf7d3d9742c90049e2e73"

      define_method(:install) do
        bin.install "korthex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Orwell-Yu/korthex/releases/download/v0.1.0/korthex_0.1.0_linux_amd64.tar.gz"
      sha256 "ae820f1a61a7a6956dc4f9c3f8f525d26f54c5f9588e6600744bca825345dc7c"
      define_method(:install) do
        bin.install "korthex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Orwell-Yu/korthex/releases/download/v0.1.0/korthex_0.1.0_linux_arm64.tar.gz"
      sha256 "3eae73840b2385ccdfecd7ec69e2f9acd334472c505b85d11b7e165eb18ff17d"
      define_method(:install) do
        bin.install "korthex"
      end
    end
  end

  test do
    system "#{bin}/korthex", "--version"
  end
end
